version: "3"
volumes:
  wireguard-ui-config:
  wireguard-ui-db:
networks:
  nginxproxymanager_default:
    external: true
services:
  wg:
    build: .
    #image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - .wireguard-ui-db:/app/db
      - wireguard-ui-config:/etc/wireguard
    networks:
      - nginxproxymanager_default
